//! Device Tree Module
//! 设备树模块
//!
//! This module handles parsing of device tree files (.dts).

use std::fs;
use std::path::PathBuf;

/// Find device tree file for a given board
/// 查找指定开发板的设备树文件
/// 
/// New structure: platform/board/<vendor>/<board_name>/<board_name>.dts
pub fn find_device_tree_file(board_name: &str) -> Option<PathBuf> {
    let root = super::root_path::get_root_path();
    let root_path = PathBuf::from(&root);
    let platform_path = root_path.join("platform").join("board");
    
    if let Ok(entries) = fs::read_dir(&platform_path) {
        for vendor_entry in entries.flatten() {
            let vendor_path = vendor_entry.path();
            if vendor_path.is_dir() {
                let board_path = vendor_path.join(board_name);
                if board_path.is_dir() {
                    let dts_path = board_path.join(format!("{}.dts", board_name));
                    if dts_path.exists() {
                        return Some(dts_path);
                    }
                }
            }
        }
    }
    None
}

/// Find chip device tree file
/// 查找芯片设备树文件
/// 
/// New structure: platform/chip/<vendor>/<chip_name>/<chip_name>.dts
pub fn find_chip_device_tree_file(chip_name: &str) -> Option<PathBuf> {
    let root = super::root_path::get_root_path();
    let root_path = PathBuf::from(&root);
    let platform_path = root_path.join("platform").join("chip");
    
    if let Ok(entries) = fs::read_dir(&platform_path) {
        for vendor_entry in entries.flatten() {
            let vendor_path = vendor_entry.path();
            if vendor_path.is_dir() {
                let chip_path = vendor_path.join(chip_name);
                if chip_path.is_dir() {
                    let dts_path = chip_path.join(format!("{}.dts", chip_name));
                    if dts_path.exists() {
                        return Some(dts_path);
                    }
                }
            }
        }
    }
    None
}

/// Generate device tree information as Rust code
/// 将设备树信息生成为 Rust 代码
pub fn generate_device_tree_info(dts_content: &str) -> Result<String, String> {
    let mut output = String::new();
    
    output.push_str("//! Device Tree Generated Code\n");
    output.push_str("//! 设备树生成的代码\n\n");
    output.push_str("//! This file is automatically generated by build_tool.\n");
    output.push_str("//! Do not edit manually.\n\n");
    
    output.push_str("use core::mem::size_of;\n\n");
    
    // Parse simple device tree properties
    for line in dts_content.lines() {
        let line = line.trim();
        
        // Parse compatible property
        if line.contains("compatible") {
            if let Some(compat) = extract_string_property(line) {
                output.push_str("pub const DEVICE_COMPATIBLE: &str = \"");
                output.push_str(&compat);
                output.push_str("\";\n");
            }
        }
        
        // Parse model property
        if line.contains("model") {
            if let Some(model) = extract_string_property(line) {
                output.push_str("pub const DEVICE_MODEL: &str = \"");
                output.push_str(&model);
                output.push_str("\";\n");
            }
        }
        
        // Parse #address-cells and #size-cells
        if line.contains("#address-cells") {
            if let Some(val) = extract_number_property(line) {
                output.push_str(&format!("pub const ADDRESS_CELLS: u32 = {};\n", val));
            }
        }
        
        if line.contains("#size-cells") {
            if let Some(val) = extract_number_property(line) {
                output.push_str(&format!("pub const SIZE_CELLS: u32 = {};\n", val));
            }
        }
    }
    
    output.push_str("\n");
    output.push_str("/// Device tree base addresses\n");
    output.push_str("/// 设备树基地址\n");
    output.push_str("#[derive(Debug, Clone, Copy)]\n");
    output.push_str("pub struct DeviceTree {\n");
    output.push_str("    pub base_address: u32,\n");
    output.push_str("    pub size: u32,\n");
    output.push_str("}\n\n");
    
    if dts_content.contains("memory") {
        output.push_str("/// Memory regions from device tree\n");
        output.push_str("pub const MEMORY_REGIONS: &[DeviceTree] = &[];\n");
    }
    
    if dts_content.contains("interrupt-controller") {
        output.push_str("/// Interrupt controller present\n");
        output.push_str("pub const HAS_INTERRUPT_CONTROLLER: bool = true;\n");
    }
    
    if dts_content.contains("clocks") {
        output.push_str("/// Clock controller present\n");
        output.push_str("pub const HAS_CLOCK_CONTROLLER: bool = true;\n");
    }
    
    Ok(output)
}

fn extract_string_property(line: &str) -> Option<String> {
    let start = line.find('"')?;
    let end = line[start + 1..].find('"')?;
    let s = &line[start + 1..start + 1 + end];
    Some(s.to_string())
}

fn extract_number_property(line: &str) -> Option<u32> {
    let parts: Vec<&str> = line.split('=').collect();
    if parts.len() >= 2 {
        let value = parts[1].trim().trim_end_matches(';').trim();
        return value.parse().ok();
    }
    None
}
