//! Linker Script Module
//! 链接脚本模块
//!
//! This module generates linker scripts (link.x) for boot and kernel.
//! 用于为 boot 和 kernel 生成链接脚本

use super::config::BoardConfig;

/// Generate linker script for bootloader
/// 为引导程序生成链接脚本
///
/// # Arguments
/// * `config` - Board configuration
///
/// # Returns
/// Linker script content as String
pub fn generate_boot_linker_script(config: &BoardConfig) -> String {
    let mut script = String::new();
    
    script.push_str("/*\n");
    script.push_str(" * Bootloader Linker Script\n");
    script.push_str(" * 引导程序链接脚本\n");
    script.push_str(" *\n");
    script.push_str(" * Auto-generated by build_tool\n");
    script.push_str(" * 由 build_tool 自动生成\n");
    script.push_str(" */\n\n");
    
    script.push_str("MEMORY\n");
    script.push_str("{\n");
    script.push_str(&format!("    FLASH (rx)  : ORIGIN = 0x{:08X}, LENGTH = {}K\n", 
        config.boot_base, config.boot_size / 1024));
    script.push_str(&format!("    RAM (rwx)   : ORIGIN = 0x{:08X}, LENGTH = {}K\n", 
        config.sram_base, config.sram_size / 1024));
    script.push_str("}\n\n");
    
    script.push_str("ENTRY(_start)\n\n");
    
    script.push_str("SECTIONS\n");
    script.push_str("{\n");
    script.push_str("    .text :\n");
    script.push_str("    {\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("        KEEP(*(.vector_table))\n");
    script.push_str("        *(.text*)\n");
    script.push_str("        *(.rodata*)\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("    } > FLASH\n\n");
    
    script.push_str("    .data :\n");
    script.push_str("    {\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("        *(.data*)\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("    } > RAM AT > FLASH\n\n");
    
    script.push_str("    .bss :\n");
    script.push_str("    {\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("        *(.bss*)\n");
    script.push_str("        *(COMMON)\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("    } > RAM\n\n");
    
    script.push_str("    /DISCARD/ :\n");
    script.push_str("    {\n");
    script.push_str("        libc.a(*)\n");
    script.push_str("        libm.a(*)\n");
    script.push_str("        libgcc.a(*)\n");
    script.push_str("    }\n");
    
    script.push_str("}\n");
    
    script
}

/// Generate linker script for kernel
/// 为内核生成链接脚本
///
/// # Arguments
/// * `config` - Board configuration
///
/// # Returns
/// Linker script content as String
pub fn generate_kernel_linker_script(config: &BoardConfig) -> String {
    let mut script = String::new();
    
    script.push_str("/*\n");
    script.push_str(" * Kernel Linker Script\n");
    script.push_str(" * 内核链接脚本\n");
    script.push_str(" *\n");
    script.push_str(" * Auto-generated by build_tool\n");
    script.push_str(" * 由 build_tool 自动生成\n");
    script.push_str(" */\n\n");
    
    script.push_str("MEMORY\n");
    script.push_str("{\n");
    script.push_str(&format!("    FLASH (rx)  : ORIGIN = 0x{:08X}, LENGTH = {}K\n", 
        config.kernel_base, config.kernel_size / 1024));
    script.push_str(&format!("    RAM (rwx)   : ORIGIN = 0x{:08X}, LENGTH = {}K\n", 
        config.sram_base, config.sram_size / 1024));
    script.push_str("}\n\n");
    
    script.push_str("ENTRY(_start)\n\n");
    
    script.push_str("SECTIONS\n");
    script.push_str("{\n");
    script.push_str("    .text :\n");
    script.push_str("    {\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("        KEEP(*(.vector_table))\n");
    script.push_str("        *(.text*)\n");
    script.push_str("        *(.rodata*)\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("    } > FLASH\n\n");
    
    script.push_str("    .data :\n");
    script.push_str("    {\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("        *(.data*)\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("    } > RAM AT > FLASH\n\n");
    
    script.push_str("    .bss :\n");
    script.push_str("    {\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("        *(.bss*)\n");
    script.push_str("        *(COMMON)\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str("    } > RAM\n\n");
    
    script.push_str("    .stack :\n");
    script.push_str("    {\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str(&format!("        . = . + {};\n", config.kernel_stack_size));
    script.push_str("        *(.stack*)\n");
    script.push_str("    } > RAM\n\n");
    
    script.push_str("    .heap :\n");
    script.push_str("    {\n");
    script.push_str("        . = ALIGN(4);\n");
    script.push_str(&format!("        . = . + {};\n", config.kernel_heap_size));
    script.push_str("        *(.heap*)\n");
    script.push_str("    } > RAM\n\n");
    
    script.push_str("    /DISCARD/ :\n");
    script.push_str("    {\n");
    script.push_str("        libc.a(*)\n");
    script.push_str("        libm.a(*)\n");
    script.push_str("        libgcc.a(*)\n");
    script.push_str("    }\n");
    
    script.push_str("}\n");
    
    script
}
